// <auto-generated />
using Aderis.OpcuaInjection.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Aderis.OpcuaInjection.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240718023204_AddClientConfig")]
    partial class AddClientConfig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Aderis.OpcuaInjection.Models.BrowseExclusionFolder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ConnectionOpcClientConnectionId")
                        .HasColumnType("integer");

                    b.Property<string>("ExclusionFolder")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OpcClientConnectionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OpcClientConnectionId");

                    b.ToTable("BrowseExclusionFolders");
                });

            modelBuilder.Entity("Aderis.OpcuaInjection.Models.OpcClientConnection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConnectionName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("EncryptedPassword")
                        .HasColumnType("bytea");

                    b.Property<int>("MaxSearch")
                        .HasColumnType("integer");

                    b.Property<int>("TimeoutMs")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("OpcClientConnections");
                });

            modelBuilder.Entity("Aderis.OpcuaInjection.Models.BrowseExclusionFolder", b =>
                {
                    b.HasOne("Aderis.OpcuaInjection.Models.OpcClientConnection", "OpcClientConnection")
                        .WithMany("BrowseExclusionFolders")
                        .HasForeignKey("OpcClientConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OpcClientConnection");
                });

            modelBuilder.Entity("Aderis.OpcuaInjection.Models.OpcClientConnection", b =>
                {
                    b.Navigation("BrowseExclusionFolders");
                });
#pragma warning restore 612, 618
        }
    }
}
